make:
  @echo Print out the frequencies: make analyze ARGS="filename"
  @echo Decode the text: make decode ARGS="filename"

analyze:
  python3 frequency.py $(ARGS)

decode:
  python3 subcipher.py $(ARGS)
